//! Parity against Python misaki. The corpus is generated by
//! `tools/gen_golden.py` -- regenerate it, never hand-edit it.
//!
//! Words not in the lexicon fall to espeak in the reference implementation.
//! This crate has no espeak dependency, so those cases are skipped here and
//! covered by the binary's integration test instead.

use std::collections::HashMap;

/// `key_field` is "word" for words.json, "text" for sentences.json.
fn load(name: &str, key_field: &str) -> Vec<(String, String)> {
    let raw = std::fs::read_to_string(format!("tests/golden/{name}")).expect("golden file");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("valid golden json");
    v["cases"]
        .as_array()
        .expect("cases array")
        .iter()
        .filter_map(|c| {
            Some((c[key_field].as_str()?.to_string(), c["phonemes"].as_str()?.to_string()))
        })
        .collect()
}

#[test]
fn word_level_parity_is_high() {
    let g = sayd_misaki_en::G2p::new(false);
    let cases = load("words.json", "word");
    assert!(cases.len() > 1000, "corpus too small: {}", cases.len());

    let lex = sayd_misaki_en::Lexicon::new(false); // hoisted: building it per word is wasteful
    let mut hit = 0usize;
    let mut compared = 0usize;
    let mut failures: Vec<(String, String, String)> = Vec::new();
    for (word, expected) in &cases {
        // Only score words the lexicon actually knows -- either under the
        // exact spelling or, mirroring G2p::word's lowercase fallback, under
        // its lowercased form (e.g. capitalized words like "Admit" resolve
        // via the lowercase entry). espeak-fallback words are the binary's
        // problem, not this crate's.
        let lower = word.to_lowercase();
        if lex.raw(word).is_none() && lex.raw(&lower).is_none() {
            continue;
        }
        compared += 1;
        let got = g.phonemize(word);
        if &got == expected {
            hit += 1;
        } else if failures.len() < 20 {
            failures.push((word.clone(), expected.clone(), got));
        }
    }
    let pct = 100.0 * hit as f64 / compared as f64;
    let total = cases.len();
    let total_failures = compared - hit;
    let failures_shown = failures.len();
    println!("word parity: {hit}/{compared} ({pct:.1}%); {total_failures} failures, {failures_shown} shown; compared {compared}/{total} of the corpus");
    for (w, e, g) in &failures {
        println!("  {w}: expected {e:?}, got {g:?}");
    }
    let min_compared = (cases.len() * 9) / 10;
    assert!(compared >= min_compared, "coverage {:.1}% below 90% threshold: {}/{} of corpus scored", 100.0 * compared as f64 / cases.len() as f64, compared, cases.len());
    assert!(pct >= 99.0, "word parity {pct:.1}% below the 99.0% floor");
}

// The corpus sentences (tests/golden/sentences.json) include date constructs
// (03/04/2026, 2026-08-10) and non-dollar currencies (£, €) that this port
// deliberately does not handle — these are listed as Future Work in the plan.
// A byte-exact sentence-level parity assertion would fail for reasons unrelated
// to this crate's scope, so we test only number-heavy cases here instead.
#[test]
fn number_heavy_sentences_normalize_correctly() {
    let g = sayd_misaki_en::G2p::new(false);
    let expectations: HashMap<&str, &str> = [
        ("$1,234.56", "dˈɑləɹz"),
        ("50%", "pəɹsˈɛnt"),
        ("the 1st", "fˈɜɹst"),
    ]
    .into_iter()
    .collect();
    for (input, must_contain) in expectations {
        let got = g.phonemize(input);
        assert!(got.contains(must_contain), "{input} -> {got:?}, missing {must_contain:?}");
    }
}
